"""update type tables

Revision ID: 286956034186
Revises: d871e281cb20
Create Date: 2026-07-07 15:57:32.786921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '286956034186'
down_revision: Union[str, Sequence[str], None] = 'd871e281cb20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_type', sa.Column('code', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'device_type', ['code'])
    op.add_column('role_type', sa.Column('code', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'role_type', ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role_type', type_='unique')
    op.drop_column('role_type', 'code')
    op.drop_constraint(None, 'device_type', type_='unique')
    op.drop_column('device_type', 'code')
    # ### end Alembic commands ###
