"""add activate_code to gateway

Revision ID: 731c76ad9745
Revises: 7832691bf31f
Create Date: 2026-08-29 21:45:20.424682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '731c76ad9745'
down_revision: Union[str, Sequence[str], None] = '7832691bf31f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gateway_device', sa.Column('activate_code_hash', sa.String(), nullable=True))
    op.add_column('gateway_device', sa.Column('activate_code_expire_time', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'gateway_device', ['activate_code_hash'])
    op.drop_column('gateway_device', 'token_lookup')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gateway_device', sa.Column('token_lookup', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'gateway_device', type_='unique')
    op.drop_column('gateway_device', 'activate_code_expire_time')
    op.drop_column('gateway_device', 'activate_code_hash')
    # ### end Alembic commands ###
