"""add token_lookup

Revision ID: 7832691bf31f
Revises: b939a86e73e9
Create Date: 2026-07-21 23:38:52.967392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7832691bf31f'
down_revision: Union[str, Sequence[str], None] = 'b939a86e73e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gateway_device', sa.Column('token_lookup', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gateway_device', 'token_lookup')
    # ### end Alembic commands ###
