"""update database

Revision ID: 85634354075e
Revises: da46d285a0f0
Create Date: 2026-07-04 19:51:58.683287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85634354075e'
down_revision: Union[str, Sequence[str], None] = 'da46d285a0f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('role_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    op.create_table('session',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.Column('expires_time', sa.DateTime(), nullable=False),
    sa.Column('last_activity_time', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gateway_device',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('mac_address', sa.String(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['system_id'], ['system.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mac_address'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('sensor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('mac_address', sa.String(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['system_id'], ['system.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['device_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mac_address')
    )
    op.create_table('user_to_system',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role_type.id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['system.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('admin')
    op.drop_table('system_to_observer')
    op.drop_table('system_device')
    op.drop_table('observer')
    op.drop_constraint(op.f('connected_device_code_key'), 'connected_device', type_='unique')
    op.drop_column('connected_device', 'password_hash')
    op.drop_column('connected_device', 'code')
    op.create_unique_constraint(None, 'device_type', ['type'])
    op.add_column('system', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('system_admin_id_fkey'), 'system', type_='foreignkey')
    op.create_foreign_key(None, 'system', '_user', ['owner_id'], ['id'])
    op.drop_column('system', 'admin_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system', sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'system', type_='foreignkey')
    op.create_foreign_key(op.f('system_admin_id_fkey'), 'system', 'admin', ['admin_id'], ['id'])
    op.drop_column('system', 'owner_id')
    op.drop_constraint(None, 'device_type', type_='unique')
    op.add_column('connected_device', sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('connected_device', sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('connected_device_code_key'), 'connected_device', ['code'], postgresql_nulls_not_distinct=False)
    op.create_table('observer',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('observer_pkey'))
    )
    op.create_table('system_device',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('mac_address', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('system_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['system_id'], ['system.id'], name=op.f('system_device_system_id_fkey')),
    sa.ForeignKeyConstraint(['type_id'], ['device_type.id'], name=op.f('system_device_type_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('system_device_pkey')),
    sa.UniqueConstraint('code', name=op.f('system_device_code_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('mac_address', name=op.f('system_device_mac_address_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('system_to_observer',
    sa.Column('system_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('observer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['observer_id'], ['observer.id'], name=op.f('system_to_observer_observer_id_fkey')),
    sa.ForeignKeyConstraint(['system_id'], ['system.id'], name=op.f('system_to_observer_system_id_fkey')),
    sa.PrimaryKeyConstraint('system_id', 'observer_id', name=op.f('system_to_observer_pkey'))
    )
    op.create_table('admin',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('admin_pkey'))
    )
    op.drop_table('user_to_system')
    op.drop_table('sensor')
    op.drop_table('gateway_device')
    op.drop_table('session')
    op.drop_table('role_type')
    op.drop_table('_user')
    # ### end Alembic commands ###
