"""update database

Revision ID: b939a86e73e9
Revises: af2532253045
Create Date: 2026-07-18 00:58:52.209614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b939a86e73e9'
down_revision: Union[str, Sequence[str], None] = 'af2532253045'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gateway_device', 'mac_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gateway_device', 'mac_address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
